### PR TITLE
Drop support for python 2 and FIX: #22 - AttributeError: module 'docutils.nodes' has no attribute '…

### PR DESCRIPTION
**Pull request by antoinecollet5**
See #22 .

AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'. reprunicode is a compatibility hack for python 2. It has been removed from docutils in v0.21.

In this PR, we check if python is v2 or v3 and implement the correct behavior.

### CODE REVIEW

**Comment by a-detiste** [comment]
Please remove Python2 support altogether

**Comment by jbloom** [comment]
It would be great if this pull request could be merged as I am having this same error when running with the newest `docutils`.

**Comment by antoinecollet5** [comment]
> Please remove Python2 support altogether

@a-detiste I am not sure this is desired by contributors ? But the last update to the repo was 5 years ago...

@vidartf could you give us your opinion and merge this PR ?

**Comment by jbloom** [comment]
I really think something like this needs to be merged if `nbsphinx-link` is going to stay usable, which I hope it will!

**Comment by vidartf** [comment]
I am currently on vacation, but will look at this next week. Please ping me
again if I forget!

**Comment by antoinecollet5** [comment]
@vidartf as requested, I ping you :)
If you do not have time to maintain the project, you need to find other maintainers. I can help you with that if needed.

**Comment by vidartf** [comment]
@antoinecollet5  I had a look, and agree with @a-detiste that py2 support should be dropped. Please remove that logic and instead add a `python_requires` phrase in the setup.py file. I have no particular opinions about which versions to include there, so probably just put `>= 3.8` as that is all non-EOL Pythons?

Help with maintenance is always appreciated, but this is a very lightweight package, and the only reason I didn't reply was that I didn't spot the activity until I was pinged (I'll blame my configuration of GH notifications for that). Please do continue opening PRs though! :)

**Comment by a-detiste** [comment]
Here's the patch used in Debian 

https://sources.debian.org/src/nbsphinx-link/1.3.0-4/debian/patches/patch_1078311_reprunicode.patch/

**Comment by a-detiste** [comment]
Here's the patch used in Debian 

https://sources.debian.org/src/nbsphinx-link/1.3.0-4/debian/patches/patch_1078311_reprunicode.patch/

**Comment by antoinecollet5** [comment]
> @antoinecollet5 I had a look, and agree with @a-detiste that py2 support should be dropped. Please remove that logic and instead add a `python_requires` phrase in the setup.py file. I have no particular opinions about which versions to include there, so probably just put `>= 3.8` as that is all non-EOL Pythons?
> 
> Help with maintenance is always appreciated, but this is a very lightweight package, and the only reason I didn't reply was that I didn't spot the activity until I was pinged (I'll blame my configuration of GH notifications for that). Please do continue opening PRs though! :)

Ok @a-detiste , @vidartf  I renamed the PR to indicate drop of python2 and made the changes..

**Comment by antoinecollet5** [comment]
@vidartf @a-detiste could you please review this PR and merge it ?
AC

**Review by vidartf — APPROVED** [review]

**Comment by vidartf** [comment]
Thanks a million for fixing! 🚀

**Pull request merged**
